version: '3'

services:

  payload:
    image: ghcr.io/guillermoscript/ai-project:latest
    expose:
      - "3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - app-network

  python:
    image: ghcr.io/guillermoscript/ai-project/Python:latest
    expose: 
      - "5000"

networks:
  app-network:
    driver: bridge

volumes:
  data:
  node_modules:
